### ISSUE TITLE
I published this repo

### ISSUE THREAD

**Issue by PGDataHome** [fr-ser/faust-bugs#1]
https://github.com/PGDataHome/faust_445/blob/master/README.md

does it seem you could now reproduce the bug situation ?

**Comment by fr-ser** [comment]
When I remove the `maybe_declare` from your tableofset.py I can run the example.

Als the log you put into the repo shows this error: 
`ModuleNotFoundError: No module named 'examples'`

This is probably more of a problem of how you run the application.
Also in your Pipfile there is no Faust. So best case is you have it installed globally and it just works by luck.
